name: Run tests

on: [push]

jobs:
  run-tests:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [2.7, 3.5, 3.6, 3.7]
        include:
        - os: ubuntu-latest
          os-name: Linux
          pip-cache-path: ~/.cache/pip
        - os: windows-latest
          os-name: w32
          pip-cache-path: ~\AppData\Local\pip\Cache

    name: Python ${{ matrix.python-version }} @ ${{ matrix.os-name }}
    runs-on: ${{ matrix.os }}

    steps:

      # Setup Python/pip
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ${{ matrix.pip-cache-path }}
          key: ${{ runner.os }}-pip

      # Setup tox
      - name: Install dependencies
        run: |
          python --version
          python -m pip install --upgrade "pip<21.0" "setuptools<45" wheel
          pip --version
          pip install --upgrade virtualenv tox
      - name: Set PYVER
        run: |
          import os, sys
          pyver = '%d%d' % tuple(sys.version_info[:2])
          with open(os.environ['GITHUB_ENV'], 'a') as f:
            f.write('PYVER=' + pyver + '\n')
        shell: python

      - name: Run tox @ Linux
        run:
          tox -e py$PYVER
        if: ${{ runner.os == 'Linux' }}
      - name: Run tox @ w64
        run:
          tox -e py%PYVER%
        shell: cmd
        if: ${{ runner.os == 'Windows' }}
